### ISSUE TITLE
Unable to build the module due to 'UNRESOLVED_IMPORT' errors in rollup.js

### ISSUE THREAD

**Issue by pccracker** [abacritt/angularx-social-login#108]
I'm trying to build the module after some changes but i'm getting UNRESOLVED_IMPORT errors from the rollup.js module, this is the full output of `npm run build`:

```
Inlining succeeded.
ES2015 compilation succeeded.
ES5 compilation succeeded.
Typings and metadata copy succeeded.
All bundles generated successfully.
(node:3424) UnhandledPromiseRejectionWarning: Error: Could not resolve './src/entities/base-login-provider' from out-tsc/lib-es2015/angularx-social-login.js
    at error (/node/node_modules/angularx-social-login/node_modules/rollup/dist/rollup.js:199:15)
    at /node/node_modules/angularx-social-login/node_modules/rollup/dist/rollup.js:20784:25
    at <anonymous>
(node:3424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3424) UnhandledPromiseRejectionWarning: Error: Could not resolve './src/entities/base-login-provider' from out-tsc/lib-es5/angularx-social-login.js
    at error (/node/node_modules/angularx-social-login/node_modules/rollup/dist/rollup.js:199:15)
    at /node/node_modules/angularx-social-login/node_modules/rollup/dist/rollup.js:20784:25
    at <anonymous>
(node:3424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3424) UnhandledPromiseRejectionWarning: Error: Could not resolve './src/entities/base-login-provider' from out-tsc/lib-es5/angularx-social-login.js
    at error (/node/node_modules/angularx-social-login/node_modules/rollup/dist/rollup.js:199:15)
    at /node/node_modules/angularx-social-login/node_modules/rollup/dist/rollup.js:20784:25
    at <anonymous>
(node:3424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:3424) UnhandledPromiseRejectionWarning: Error: Could not resolve './src/entities/base-login-provider' from out-tsc/lib-es5/angularx-social-login.js
    at error (/node/node_modules/angularx-social-login/node_modules/rollup/dist/rollup.js:199:15)
    at /node/node_modules/angularx-social-login/node_modules/rollup/dist/rollup.js:20784:25
    at <anonymous>
(node:3424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

```

**Comment by jaibatrik** [comment]
Did you make any change to the folder structure? Building works fine for me.
