### ISSUE TITLE
AoT not working again

### ISSUE THREAD

**Issue by filipemendes1994** [abacritt/angularx-social-login#22]
Well, I am using this plugin (awesome btw!), but I can't do a AoT build because of it.
This is my `app.module.ts` and my `ng build --prod` stacktrace 

```TypeScript
import { NgModule } from '@angular/core';
(...)

const config = new AuthServiceConfig([
  {
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider('583729964953-colv9g62m813om4s1p5thtlqdv9ig46c.apps.googleusercontent.com')
  },
  {
    id: FacebookLoginProvider.PROVIDER_ID,
    provider: new FacebookLoginProvider('347701065702510')
  }
]);

export function provideConfig() {
  return config;
}

@NgModule({
      imports: [
          (...)
          SocialLoginModule
      ],
      declarations: [
          AppComponent,
          LoginComponent,
          HomeComponent,
          FestivalsComponent
      ],
      providers: [
          (...),
          {
            provide: AuthServiceConfig,
            useFactory: provideConfig
          }
      ],
      bootstrap: [AppComponent]
  })

  export class AppModule { }
```

```
filipemendes@MacBook-Pro-de-Filipe:~/dev/mistaker-maker/web-app$ ng build --prod
Date: 2017-11-18T23:27:07.414Z                                                          
Hash: b7566c89f11e42ae3006
Time: 37673ms
chunk {0} main.d383bc3ff89eb6533d48.bundle.js (main) 659 kB [initial] [rendered]
chunk {1} polyfills.e6475d2787bb3154d59c.bundle.js (polyfills) 60.9 kB [initial] [rendered]
chunk {2} styles.532043307593380cd798.bundle.css (styles) 234 bytes [initial] [rendered]
chunk {3} inline.e5a722ba293bced87b37.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:9341:17)
    at assignContextualParameterTypes (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:41948:29)
    at checkExpressionWorker (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:42959:28)
    at checkExpression (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:42898:42)
    at checkExpressionCached (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:42779:38)
    at checkReturnStatement (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:45418:54)
    at checkSourceElement (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46763:28)
    at Object.forEach (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:1506:30)
    at checkBlock (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:44563:16)
    at checkSourceElement (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:41990:21)
    at checkDeferredNodes (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46828:25)
    at checkSourceFileWorker (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46863:17)
    at checkSourceFile (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46842:13)
    at Object.forEach (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:1506:30)
 @ ./node_modules/rxjs/observable/bindCallback.js 2:32-68
 @ ./node_modules/rxjs/add/observable/bindCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/angular4-social-login/angular4-social-login.umd.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:9341:17)
    at assignContextualParameterTypes (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:41948:29)
    at checkExpressionWorker (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:42959:28)
    at checkExpression (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:42898:42)
    at checkExpressionCached (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:42779:38)
    at checkReturnStatement (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:45418:54)
    at checkSourceElement (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46763:28)
    at Object.forEach (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:1506:30)
    at checkBlock (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:44563:16)
    at checkSourceElement (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:41990:21)
    at checkDeferredNodes (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46828:25)
    at checkSourceFileWorker (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46863:17)
    at checkSourceFile (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:46842:13)
    at Object.forEach (/Users/filipemendes/dev/mistaker-maker/web-app/node_modules/typescript/lib/typescript.js:1506:30)
 @ ./node_modules/rxjs/observable/bindNodeCallback.js 2:36-76
 @ ./node_modules/rxjs/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/angular4-social-login/angular4-social-login.umd.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

I hope someone can help me, please

**Comment by l4k4i** [comment]
I solved this by removing node_modules and changing typescript and rxjs versions to "latest" in package.json

**Comment by jaibatrik** [comment]
Should be fixed with the latest release. Make sure the dependencies are met. Reopen if you still see the issue and a simple sample would help a lot :)
