### ISSUE TITLE
Angular16 : ERROR Error: Uncaught (in promise): You should not call this method directly for Google, use "<asl-google-signin-button>" wrapper or generate the button yourself with "google.accounts.id.renderButton()

### ISSUE THREAD

**Issue by DKGit2022** [abacritt/angularx-social-login#723]
I am doing angular social login with google and facing bellow error on button click.

ERROR Error: Uncaught (in promise): You should not call this method directly for Google, use "<asl-google-signin-button>" wrapper or generate the button yourself with "google.accounts.id.renderButton()" (https://developers.google.com/identity/gsi/web/guides/display-button#javascript)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25990:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25990:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:26300:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)

**Comment by DKGit2022** [comment]
And On page load
![PageLoad](https://github.com/abacritt/angularx-social-login/assets/104298745/76fb79da-bfd4-43e1-a2bc-ba5cd89a3119)

**Comment by DKGit2022** [comment]
Any one can help me

**Comment by DKGit2022** [comment]
Here is my code

**app.component.ts**

import { Component,OnInit } from '@angular/core';
import { AuthServiceService } from './appServices/auth-service.service';
import { GoogleLoginProvider, SocialAuthService } from '@abacritt/angularx-social-login';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  title = 'GoogleLoginApp';

  constructor(private authServiceService: AuthServiceService, private socialAuthService: SocialAuthService) { }

  ngOnInit(): void {

  }

  onGoogleSignIn() {
    this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID).then((res)=>{
      alert('Sucess');
      console.log(res);
    });
  }
}

**app.Component.html**
<button (click)="onGoogleSignIn()">Sign In Google</button>

**app.module.ts**
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { SocialLoginModule, SocialAuthServiceConfig } from '@abacritt/angularx-social-login';
import {
  GoogleLoginProvider,
  FacebookLoginProvider
} from '@abacritt/angularx-social-login';
import { HttpClientModule } from '@angular/common/http';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';



@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    SocialLoginModule,
    HttpClientModule
  ],
  providers: [
    {
      provide: 'SocialAuthServiceConfig',
      useValue: {
        autoLogin: false,
        providers: [
          {
            id: GoogleLoginProvider.PROVIDER_ID,
            provider: new GoogleLoginProvider(
              '917274762375-ledobcbb0b0ncpiqlb3ir.apps.googleusercontent.com'
            )
          }
        ],
        onError: (err) => {
          console.error(err);
        }
      } as SocialAuthServiceConfig,
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by ted-mundy** [comment]
I'm also getting this error

**Comment by DKGit2022** [comment]
That is incorrect Id.
Thanks

**Comment by konlanz** [comment]
so do this  npm install --save @types/google.accounts

And use this as your login buttun <asl-google-signin-button class=""></asl-google-signin-button>

Don't use the function you road for the google login

**Comment by jayna456** [comment]
Is there any solution to resolve the issue?

**Comment by ted-mundy** [comment]
> Is there any solution to resolve the issue?

I just ended up resorting to building my own google sign-in process

**Comment by gambheera** [comment]
I'm also getting the same error. I checked the ClientId twice and no issue with the clientId. But still I'm facing the same issue :(

**Comment by furevor** [comment]
Also have this error with the similar code from some guides like [this](https://www.positronx.io/angular-google-social-login-tutorial-with-example)

**Comment by klebermachado** [comment]
Why does the library force me to use Google's design pattern for the login button, even though it doesn't fit the layout of my app?

I want to apply my own style. Is it possible to implement this with the library?
