### ISSUE TITLE
Google Login Issue

### ISSUE THREAD

**Issue by aelshemy16** [abacritt/angularx-social-login#76]
Google after choose account should return user data but i faced this 

`Error
Close
Runtime Error
Uncaught (in promise): [object Object]
Stack
Error: Uncaught (in promise): [object Object]
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at http://localhost:8100/build/polyfills.js:3:19174
    at http://localhost:8100/build/vendor.js:60281:21
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4484:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4475:37)
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 9.4.0
OS Platform: OS X El Capitan
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36`

**Comment by jaibatrik** [comment]
Can you provide a sample where you are seeing this?

**Comment by rahulswimmer** [comment]
I use this.authService.signOut() for logout. When i try to login, the google pop up for asking which account one wants to login with, doesn't appear, instead, it logs in using the previously logged out user. I clear the session using sessionStorage.clear() when i signout. My Application is in angular 6. What should i do to get that google pop up? as thats a requirement. Thank You!

**Comment by orzsikodon** [comment]
Im facing this same exact issue. Please help
