### ISSUE TITLE
Metadata issue in angularx-social-login

### ISSUE THREAD

**Issue by ginnram** [abacritt/angularx-social-login#90]
Hello,
I have been using angular 4, and the angularx-social-login module was working fine till yesterday. But on Launching my app today using angular cli command ng serve i got this error and i cannot figure out what this is and how to solve this. Would appreciate some solution regarding this as i am stuck and cannot run my app.

ERROR in Error: Metadata version mismatch for module /home/dell/myapp/node_modules/angularx-social-login/angularx-social-login.d.ts, found version 4, expected 3, resolving symbol AuthenticationModule in /home/dell/myapp/src/app/authentication/authentication.module.ts, resolving symbol AuthenticationModule in /home/dell/myapp/src/app/authentication/authentication.module.ts, resolving symbol AuthenticationModule in /home/dell/Cateina/sharan/barosa/230518Barosa/barosa2.0.6/barosa2.0.6/src/app/authentication/authentication.module.ts
    at syntaxError (/home/dell/myapp/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/dell/myapp/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/home/dell/myapp/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/home/dell/Cateina/myapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/home/dell/myapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/dell/myapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at includeLazyRouteAndSubRoutes (/home/dell/myapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:66:25)
    at Array.reduce (<anonymous>)
    at Object.listLazyRoutesOfModule (/home/dell/myapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:54:36)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/dell/myapp/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/dell/myapp/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/dell/myapp/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by brunork26** [comment]
Did you solved the problem?

**Comment by jaibatrik** [comment]
Likely not related to the library. But will investigate if we get a sample.

**Comment by brunork26** [comment]
When I installed for the first time I used npm install --save angularx-social-login, my application was running at this time, and everything worked well. The next day I started the application again and got the same error as ginnram. 

My sollution for this issue was uninstall angularx-social-login and install angular4-social-login, didnt have any more errors since then.

I was using angular 4.
